stages:
  - install
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

install-dependencies:
  stage: install
  image: python:3.10
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - .cache/pip

run-tests:
  stage: test
  image: python:3.10
  script:
    - echo " Tests fictifs en cours..."
    - echo " Tous les tests ont réussi !"

deploy:
  stage: deploy
  image: python:3.10
  script:
    - echo "Déploiement réussi !"
